# This code was developed for the Evita Virtual Coach project https://www.e-vita.coach/ at AIRC AIST
# Version 4.9; Date 2023-01-20;
# Programmer: Tatsuya Kudo, PI (AIRC): Kristiina Jokinen, unless otherwise indicated.
# We thank all the Evita project partners for discussions and contributions.
# License: Apache License 2.0;
# Contact: K. Jokinen <kristiina.jokinen@aist.go.jp>

language: ja
recipe: default.v1
pipeline:
  - name: SpacyNLP
    model: "ja_ginza"
  - name: SpacyTokenizer
  # - name: SpacyEntityExtractor
  #   dimensions: ["PERSON"]
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
  - name: EntitySynonymMapper
  - name: ResponseSelector
    # retrieval_intent: out_of_scope
    # scale_loss: false
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 10
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    # enable_fallback_prediction: True
    # restrict_rules: true
    # check_for_contradictions: true
  - name: TEDPolicy
    max_history: 10
    epochs: 100

# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 10
#     epochs: 100
#   - name: RulePolicy

